name: formatMaps

on:
  pull_request:

permissions:
  contents: write

jobs:
  formatMaps:
    name: FormatMaps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SetupShinkrodb
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/varoOP/shinkrodb/releases/download/v0.1.2/shinkrodb_v0.1.2_linux_amd64.tar.gz"
          name: "shinkrodb"
          version: "0.1.2"

      - name: Check Format
        run: |
          shinkrodb format
